// Validates data/spearhead-cards.en-ko.json and writes dist/cards.js
// (a plain script so the app also works when index.html is opened from disk).
// Usage: node tools/build-cards.js
'use strict';
const fs = require('fs'), path = require('path');
const root = path.join(__dirname, '..');
const src = path.join(root, 'data', 'spearhead-cards.en-ko.json');
const out = path.join(root, 'dist', 'cards.js');
const data = JSON.parse(fs.readFileSync(src, 'utf8'));

const errors = [], ids = new Set();
const bi = (o, where) => { if (!o || typeof o.en !== 'string' || typeof o.ko !== 'string' || !o.en || !o.ko) errors.push(`${where}: missing en/ko`); };
if (data.originalTextIncluded !== false) errors.push('originalTextIncluded must be false (summaries only)');
for (const p of data.packs) {
  bi(p.name, p.id);
  const m = p.deckManifest;
  for (const c of [...p.tactics, ...p.twists]) {
    if (ids.has(c.id)) errors.push(`duplicate id ${c.id}`);
    ids.add(c.id);
    bi(c.name, c.id);
    if (c.kind === 'battle_tactic') { bi(c.score.condition, c.id + '.condition'); bi(c.command.name, c.id + '.command'); bi(c.command.mechanics, c.id + '.command.mechanics'); bi(c.command.timing, c.id + '.command.timing'); }
    if (c.kind === 'twist') { bi(c.mechanics, c.id + '.mechanics'); if (!['none', 'own_turn_end', 'round_end'].includes(c.scoreTiming)) errors.push(`${c.id}: scoreTiming`); }
  }
  const tacticIds = new Set(p.tactics.map(t => t.id));
  if (m.tacticsPerPlayer.length !== 12 || m.tacticsPerPlayer.some(id => !tacticIds.has(id))) errors.push(`${p.id}: tactic manifest`);
  for (const r of p.realms) {
    const list = m.twistsByRealm[r.id] || [];
    if (list.length !== 6) errors.push(`${p.id}/${r.id}: twist deck size ${list.length}`);
    for (const id of list) { const t = p.twists.find(x => x.id === id); if (!t || t.realmId !== r.id) errors.push(`${p.id}/${r.id}: ${id} wrong realm`); }
  }
}
const refIds = new Set(data.packs.flatMap(p => p.referenceAbilities.map(r => r.id)));
for (const i of data.issues || []) if (!ids.has(i.cardId) && !refIds.has(i.cardId)) errors.push(`issue ${i.id}: unknown card`);
if (errors.length) { console.error(errors.join('\n')); process.exit(1); }

// Optional: army option names (faction -> Spearhead army -> regiment abilities / enhancements).
const armiesSrc = path.join(root, 'data', 'spearhead-armies.json');
let armies = null;
if (fs.existsSync(armiesSrc)) {
  armies = JSON.parse(fs.readFileSync(armiesSrc, 'utf8'));
  const bad = [];
  if (!Array.isArray(armies.factions)) bad.push('factions must be an array');
  for (const f of armies.factions || []) {
    if (!f.faction || !Array.isArray(f.armies)) bad.push(`faction entry ${JSON.stringify(f).slice(0, 60)}`);
    for (const a of f.armies || []) {
      if (!a.name) bad.push(`${f.faction}: army without name`);
      for (const k of ['regimentAbilities', 'enhancements']) if (!Array.isArray(a[k]) || a[k].some(x => typeof x !== 'string' || !x)) bad.push(`${f.faction}/${a.name}: ${k}`);
    }
  }
  if (bad.length) { console.error(bad.join('\n')); process.exit(1); }
}

// The served app gets game data only; free-text notes stay in data/.
// (only issue descriptions; official-correction notes are game information and must stay)
const RESEARCH_KEYS = new Set(['description']);
const strip = v => (Array.isArray(v) ? v.map(strip) : v && typeof v === 'object'
  ? Object.fromEntries(Object.entries(v).filter(([k]) => !RESEARCH_KEYS.has(k)).map(([k, x]) => [k, strip(x)])) : v);
const publicCards = strip(data), publicArmies = armies && strip(armies);
// Only official Games Workshop links may appear in the served data.
const links = JSON.stringify([publicCards, publicArmies]).match(/https?:\/\/[^"]+/g) || [];
const foreign = links.filter(u => !/^https:\/\/(assets|www)\.warhammer-community\.com\//.test(u));
if (foreign.length) { console.error('non-official links in public data:\n' + foreign.join('\n')); process.exit(1); }

fs.writeFileSync(out, `/* Generated by tools/build-cards.js from data/*.json — do not edit by hand. */\nwindow.SPEARHEAD_CARDS = ${JSON.stringify(publicCards)};\nwindow.SPEARHEAD_ARMIES = ${JSON.stringify(publicArmies)};\n`);
const armyCount = armies ? armies.factions.reduce((s, f) => s + f.armies.length, 0) : 0;
console.log(`cards.js written: ${ids.size} cards, ${data.packs.length} packs, ${armyCount} armies`);
